"""
Django settings for pecl project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import json
import os
import sys
from datetime import timedelta
from pathlib import Path

from environ import Env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = Env()
if env.str("ECL_DJANGO_SECRET_KEY", None) is None:
    env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("ECL_DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = env.bool("ECL_DJANGO_DEBUG", False)

ALLOWED_HOSTS = json.loads(os.environ.get("ECL_DJANGO_ALLOWED_HOSTS", default="[]"))

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(asctime)s %(name)-12s %(levelname)-8s %(message)s",
        },
    },
    "handlers": {
        "console": {"level": "INFO", "class": "logging.StreamHandler", "stream": sys.stdout, "formatter": "verbose"},
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "level": "INFO",
            "handlers": ["console"],
        }
    },
}

# Application definition

INSTALLED_APPS = [
    "channels",
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "catalog",
    "agent",
    "account",
    "sync",
    "drf_yasg",
    "django_filters",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pecl.urls"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

FILE_STORAGE = env.str("FILE_STORAGE", default="local")

if FILE_STORAGE == "local":
    DEFAULT_FILE_STORAGE = "pecl.storage.LocalStorage"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = "pecl.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get("ECL_CELERY_BROKER_URL")],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": env.str("ECL_DB_NAME"),
        "USER": env.str("ECL_DB_USER"),
        "PASSWORD": env.str("ECL_DB_PASSWORD"),
        "HOST": env.str("ECL_DB_HOST"),
        "PORT": env.str("ECL_DB_PORT"),
        "ATOMIC_REQUESTS": True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "account.User"

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOWED_ORIGINS = json.loads(os.environ.get("ECL_DJANGO_CORS_ALLOWED_ORIGINS", default="[]"))

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ["rest_framework.authentication.TokenAuthentication"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
}

# SWAGGER

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {"Token": {"type": "apiKey", "name": "Authorization", "in": "header"}},
    "USE_SESSION_AUTH": False,
}

# CELERY
CELERY_BROKER_URL = env.str("ECL_CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = env.str("ECL_CELERY_RESULT_BACKEND")
CELERY_TIMEZONE = env.str("ECL_CELERY_TIMEZONE")
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BEAT_SCHEDULE = {
    "clean_uploaded_files": {
        "task": "agent.tasks.clean_uploaded_files",
        "schedule": timedelta(hours=1),
    },
}

CATALOG_LANGUAGE_MODEL_PROVIDERS = [
    "enthusiast_model_openai.OpenAILanguageModelProvider",
]

CATALOG_EMBEDDING_PROVIDERS = [
    "enthusiast_model_openai.OpenAIEmbeddingProvider",
]

# Configuration of installed plugins
CATALOG_PRODUCT_SOURCE_PLUGINS = [
    "enthusiast_source_sample.SampleProductSource",
]
CATALOG_DOCUMENT_SOURCE_PLUGINS = [
    "enthusiast_source_sample.SampleDocumentSource",
]
CATALOG_ECOMMERCE_INTEGRATION_PLUGINS: list[str] = []

CATALOG_MODELS = {
    "user": "account.models.User",
    "message": "agent.models.Message",
    "conversation": "agent.models.Conversation",
    "data_set": "catalog.models.DataSet",
    "document_chunk": "catalog.models.DocumentChunk",
    "product": "catalog.models.Product",
    "product_chunk": "catalog.models.ProductContentChunk",
    "agent": "agent.models.Agent",
}

AVAILABLE_AGENTS: list[str] = []

AVAILABLE_AGENTIC_EXECUTION_DEFINITIONS: list[str] = []

FILE_PARSER_CLASSES: dict[tuple[str] : str] = {
    (".txt",): "agent.file_parsers.text.PlainTextFileParser",
    (".pdf",): "agent.file_parsers.pdf.PDFFileParser",
    (
        ".jpg",
        ".jpeg",
        ".png",
    ): "agent.file_parsers.image.ImageFileParser",
}
UPLOADED_FILE_RETENTION_PERIOD_HOURS: int = 48

SERVICE_ACCOUNT_DOMAIN = env.str("SERVICE_ACCOUNT_DOMAIN", "enthusiast.internal")

from .settings_override import *  # noqa
