# Generated by Django 5.1.1 on 2024-12-18 19:40

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = []

    operations = [VectorExtension()]
