# Generated by Django 5.1.5 on 2025-07-03 06:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_productchunk"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductChunk",
            new_name="ProductContentChunk",
        ),
    ]
