# Generated by Django 5.2.4 on 2025-09-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_rename_productchunk_productcontentchunk"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsource",
            name="corrupted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productsource",
            name="corrupted",
            field=models.BooleanField(default=False),
        ),
    ]
