# Generated by Django 5.2.4 on 2025-09-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_documentsource_corrupted_productsource_corrupted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="properties",
            field=models.CharField(blank=True, max_length=65535),
        ),
    ]
