# Generated by Django 5.2.4 on 2025-11-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_alter_product_properties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.CharField(blank=True, max_length=65535),
        ),
    ]
