# Generated by Django 5.2.9 on 2026-01-09 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_dataset_system_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECommerceIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_name', models.CharField()),
                ('config', models.JSONField(default=dict)),
                ('data_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_integration', to='catalog.dataset')),
            ],
        ),
    ]
