FROM python:3.12

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV POETRY_VIRTUALENVS_CREATE=false

WORKDIR /app


RUN apt-get update && apt-get install -y libpq-dev

RUN curl -sSL https://install.python-poetry.org | python3 -
RUN export PATH="/root/.local/bin:$PATH"

COPY server/pyproject.dev.toml pyproject.toml
COPY plugins/ /plugins/


RUN /root/.local/bin/poetry install

COPY server/ /app/

RUN groupadd -r celery && useradd -r -g celery celery

RUN mkdir -p /app/media && \
    chown -R celery:celery /app/media && \
    chmod u+x /app/docker-entrypoint-development.sh

ENTRYPOINT ["/app/docker-entrypoint-development.sh"]