# Generated by Django 5.1.5 on 2025-01-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0002_remove_conversation_system_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="summary",
            field=models.CharField(null=True),
        ),
    ]
