# Generated by Django 5.1.5 on 2025-06-23 08:43

from django.db import migrations


def change_messages_role(apps, schema_editor):
    Message = apps.get_model("agent", "Message")
    Message.objects.filter(role="user").update(role="human")
    Message.objects.filter(role="agent").update(role="ai")
    Message.objects.filter(role="agent_error").update(role="system")


def reverse_change_messages_role(apps, schema_editor):
    Message = apps.get_model("agent", "Message")
    Message.objects.filter(role="human").update(role="user")
    Message.objects.filter(role="system").update(role="agent_error")


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0003_conversation_summary"),
    ]

    operations = [
        migrations.RunPython(change_messages_role, reverse_change_messages_role),
    ]
