# Generated by Django 5.1.5 on 2025-07-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0005_conversation_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="answer_failed",
            field=models.BooleanField(default=False),
        ),
    ]
