# Generated by Django 5.2.4 on 2025-07-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0006_message_answer_failed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="agent",
        ),
        migrations.AddField(
            model_name="conversation",
            name="agent_key",
            field=models.CharField(default="question_answer_agent", max_length=255),
        ),
    ]
