# Generated by Django 5.2.4 on 2025-08-06 07:13

import django.db.models.deletion
from django.db import migrations, models


def add_dummy_config(apps, schema_editor):
    Agent = apps.get_model("agent", "Agent")
    DataSet = apps.get_model("catalog", "DataSet")
    Conversation = apps.get_model("agent", "Conversation")
    if Conversation.objects.all().count() > 0:
        agent = Agent.objects.create(
            dataset=DataSet.objects.first(), name="placeholder", config={}, agent_type="placeholder"
        )
        Conversation.objects.update(agent=agent)


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0008_agent"),
        ("catalog", "0007_rename_productchunk_productcontentchunk"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agent",
            old_name="agent_key",
            new_name="agent_type",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="agent_key",
        ),
        migrations.AddField(
            model_name="conversation",
            name="agent",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="agent.agent"),
        ),
        migrations.AlterField(
            model_name="agent",
            name="dataset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="agents", to="catalog.dataset"
            ),
        ),
        migrations.AddConstraint(
            model_name="agent",
            constraint=models.UniqueConstraint(fields=("dataset", "name"), name="unique_agent_name_per_dataset"),
        ),
        migrations.RunPython(code=add_dummy_config, reverse_code=migrations.RunPython.noop),
    ]
