# Generated by Django 5.2.4 on 2025-08-06 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0009_rename_agent_key_agent_agent_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="agent",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="agent.agent"),
        ),
    ]
