# Generated by Django 5.2.4 on 2025-08-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0010_alter_conversation_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
