# Generated by Django 5.2.4 on 2025-08-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0011_agent_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="corrupted",
            field=models.BooleanField(default=False),
        ),
    ]
