# Generated by Django 5.2.4 on 2025-08-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0012_agent_corrupted"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="description",
            field=models.TextField(default="Lorem ipsum."),
            preserve_default=False,
        ),
    ]
