# Generated by Django 5.2.4 on 2025-08-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0013_agent_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
