# Generated by Django 5.2.4 on 2025-09-05 06:49

import django.db.models.deletion
from django.db import migrations, models

import agent.models.conversation


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0014_alter_agent_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to=agent.models.conversation.conversation_file_path)),
                ("content_type", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="files", to="agent.conversation"
                    ),
                ),
            ],
        ),
    ]
