# Generated by Django 5.2.4 on 2025-09-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0015_conversationfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationfile",
            name="llm_content",
            field=models.TextField(blank=True),
        ),
    ]
