# Generated by Django 5.2.4 on 2025-10-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0016_conversationfile_llm_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationfile",
            name="file_category",
            field=models.CharField(choices=[("image", "Image"), ("file", "File")], default="file", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="function_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
