# Generated by Django 5.2.4 on 2025-10-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0017_conversationfile_file_category_message_function_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_file",
            field=models.BooleanField(default=False),
        ),
    ]
