# Generated by Django 5.2.4 on 2025-10-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0018_message_is_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="file_upload",
            field=models.BooleanField(default=False),
        ),
    ]
