# Generated by Django 5.2.4 on 2025-10-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0019_agent_file_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("function", "Function"),
                    ("human", "Human"),
                    ("ai", "Ai"),
                    ("system", "System"),
                    ("intermediate_step", "Intermediate Step"),
                    ("file", "File"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
