# Generated by Django 5.2.4 on 2025-10-14 08:40

from django.db import migrations, models


def role_to_type(apps, schema_editor):
    Message = apps.get_model("agent", "Message")
    for message in Message.objects.all():
        if message.is_file:
            message.type = "file"
            message.save(update_fields=["type"])
            continue
        message.type = message.role
        message.save(update_fields=["type"])


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0020_message_type"),
    ]

    operations = [
        migrations.RunPython(role_to_type, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="message",
            name="is_file",
        ),
        migrations.RemoveField(
            model_name="message",
            name="role",
        ),
        migrations.AlterField(
            model_name="message",
            name="type",
            field=models.CharField(
                choices=[
                    ("function", "Function"),
                    ("human", "Human"),
                    ("ai", "Ai"),
                    ("system", "System"),
                    ("intermediate_step", "Intermediate Step"),
                    ("file", "File"),
                ],
                max_length=50,
            ),
        ),
    ]
