# Generated by Django 5.2.4 on 2025-10-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0021_remove_message_is_file_alter_message_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="file_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
