# Generated by Django 5.2.4 on 2025-10-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0022_message_file_name_message_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationfile",
            name="is_hidden",
            field=models.BooleanField(default=True),
        ),
    ]
