# Generated by Django 5.2.9 on 2026-01-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0023_conversationfile_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
