# Generated by Django 5.2.12 on 2026-03-27 08:06

import uuid

from django.db import migrations, models


def backfill_tool_call_messages(apps, schema_editor):
    """
    Pairs legacy INTERMEDIATE_STEP / FUNCTION message records that predate the tool_call_id field.
    Before this migration, tool call messages were stored without tool_call_id. Each INTERMEDIATE_STEP
    is matched with the next FUNCTION in conversation order, and a shared UUID is assigned to both.
    function_name is copied from the FUNCTION record to the paired INTERMEDIATE_STEP record.
    Orphaned records (no matching pair) are left with tool_call_id=None.
    """
    Message = apps.get_model('agent', 'Message')

    conversation_ids = (
        Message.objects
        .filter(type__in=['intermediate_step', 'function'], tool_call_id__isnull=True)
        .values_list('conversation_id', flat=True)
        .distinct()
    )

    for conversation_id in conversation_ids:
        messages = list(
            Message.objects
            .filter(
                conversation_id=conversation_id,
                type__in=['intermediate_step', 'function'],
                tool_call_id__isnull=True,
            )
            .order_by('id')
        )

        pending_intermediate = None
        updates = []

        for message in messages:
            if message.type == 'intermediate_step':
                pending_intermediate = message
            elif message.type == 'function' and pending_intermediate is not None:
                tool_call_id = str(uuid.uuid4())
                pending_intermediate.tool_call_id = tool_call_id
                if not pending_intermediate.function_name:
                    pending_intermediate.function_name = message.function_name
                message.tool_call_id = tool_call_id
                updates.extend([pending_intermediate, message])
                pending_intermediate = None

        if updates:
            Message.objects.bulk_update(updates, ['tool_call_id', 'function_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0026_agentexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tool_call_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(backfill_tool_call_messages, migrations.RunPython.noop),
    ]
