# Generated by Django 5.2.12 on 2026-04-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0027_add_tool_call_id_to_message'),
        ('catalog', '0013_ecommerceintegration'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agent',
            name='unique_agent_name_per_dataset',
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('dataset', 'name'), name='unique_agent_name_per_dataset'),
        ),
    ]
