from abc import ABC, abstractmethod

from enthusiast_common import ProductDetails
from .base import BaseRetriever


class BaseProductRetriever(BaseRetriever, ABC):
    @abstractmethod
    def find_products_matching_query(self, user_query: str) -> list[ProductDetails]:
        pass

    @abstractmethod
    def find_products_with_sql(self, sql_query: str) -> list[ProductDetails]:
        """Perform a search using an agent-generated SQL query.

        The query is sanitized and restricted to a SELECT on a single table and its
        attributes. Results are limited to the dataset configured for the retriever.

        Args:
            sql_query: A raw SQL query generated by the agent.

        Returns:
            A list of products found by the query.

        Raises:
            RetrieverError: If the SQL query is invalid.
        """
        pass

    @abstractmethod
    def get_sample_products(self, num_sample_products: int = 12) -> list[ProductDetails]:
        """Retrieve a sample of products from the dataset.

        Args:
            num_sample_products: The number of sample products to return.

        Returns:
            A list of sample products.
        """
        pass

    @abstractmethod
    def get_sample_products_json(self) -> str:
        pass

    @abstractmethod
    def product_details_as_json(self, products: list[ProductDetails]) -> list[dict]:
        """Converts ProductDetails to a dict, useful when passing it back to the agent as a JSON.

        Args:
            products: A list of ProductDetails objects.

        Returns:
            A dictionary containing a dict representation of each product.
        """
        pass
