import sqlglot
from sqlglot.errors import SqlglotError

from .retriever_sql_permission_error import RetrieverSQLPermissionError


class SQLValidator:
    def __init__(self, allowed_table_name: str, data_set_id: int):
        self._allowed_table_name = allowed_table_name
        self._data_set_id = data_set_id

    def add_data_set_id_condition_and_raise_if_not_allowed(self, sql_query: str) -> str:
        """Performs a set of checks on the SQL query generated by the agent, to make sure they only access the allowed table.
        On top of that, it ensures that the results are limited to the current data set.

        Returns:
            An updated SQL query, that includes a where condition for the data set id.
        Raises:
            RetrieverSQLPermissionError: If the query accesses tables that are not permitted.
        """
        try:
            expression = sqlglot.parse_one(sql_query)
        except SqlglotError as e:
            raise RetrieverSQLPermissionError(f"Could not parse the SQL query because of the following error {e}.")

        if not isinstance(expression, sqlglot.exp.Select):
            raise RetrieverSQLPermissionError("Only SELECT queries are allowed.")

        subqueries = [
            node for node in expression.find_all(sqlglot.exp.Select)
            if node is not expression
        ]
        if subqueries:
            raise RetrieverSQLPermissionError("Subqueries are not allowed.")

        if any(expression.find_all(sqlglot.exp.CTE)) or any(expression.find_all(sqlglot.exp.Subquery)):
            raise RetrieverSQLPermissionError("Subqueries or CTEs are not allowed.")

        for table in expression.find_all(sqlglot.exp.Table):
            if table.alias:
                raise RetrieverSQLPermissionError("Table aliases are not allowed.")

            table_name = table.name.lower()
            if table_name != self._allowed_table_name:
                raise RetrieverSQLPermissionError(f"Access to table '{table_name}' is forbidden.")

        expression_with_data_set_condition = expression.where(f"{self._allowed_table_name}.data_set_id = {self._data_set_id}")
        return expression_with_data_set_condition.sql()
